export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST'
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS'
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL'

export const PROJECT_DETAILS_REQUEST = 'PROJECT_DETAILS_REQUEST'
export const PROJECT_DETAILS_SUCCESS = 'PROJECT_DETAILS_SUCCESS'
export const PROJECT_DETAILS_FAIL = 'PROJECT_DETAILS_FAIL'
export const PROJECT_DETAILS_CLEAR = 'PROJECT_DETAILS_CLEAR'

export const PROJECT_TASKS_DETAILS_REQUEST = 'PROJECT_TASKS_DETAILS_REQUEST'
export const PROJECT_TASKS_DETAILS_SUCCESS = 'PROJECT_TASKS_DETAILS_SUCCESS'
export const PROJECT_TASKS_DETAILS_FAIL = 'PROJECT_TASKS_DETAILS_FAIL'
export const PROJECT_TASKS_DETAILS_CLEAR = 'PROJECT_TASKS_DETAILS_CLEAR'

export const PROJECT_TASKS_ALL_REQUEST = 'PROJECT_TASKS_ALL_REQUEST'
export const PROJECT_TASKS_ALL_SUCCESS = 'PROJECT_TASKS_ALL_SUCCESS'
export const PROJECT_TASKS_ALL_FAIL = 'PROJECT_TASKS_ALL_FAIL'
export const PROJECT_TASKS_ALL_CLEAR = 'PROJECT_TASKS_ALL_CLEAR'
