export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST'
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS'
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL'

export const TASK_COMPLETE_REQUEST = 'TASK_COMPLETE_REQUEST'
export const TASK_COMPLETE_SUCCESS = 'TASK_COMPLETE_SUCCESS'
export const TASK_COMPLETE_FAIL = 'TASK_COMPLETE_FAIL'

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST'
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS'
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL'

export const TASKS_REQUEST = 'TASKS_REQUEST'
export const TASKS_SUCCESS = 'TASKS_SUCCESS'
export const TASKS_FAIL = 'TASKS_FAIL'
export const TASKS_CLEAR = 'TASKS_CLEAR'
